Repository vmware/terraform-provider-vcd, pull requests merged in 2018-11, with the labels that each got.

#109 Improve catalog item
  vcd/resource_vcd_catalog_item.go
Labels: size/XS

#110 Fix error "runtime: kevent on fd 4 failed with 9" when running test.
  vcd/resource_vcd_catalog_item.go
Labels: size/XS

#115 Update vendor with vCD API upgrade
  vendor/github.com/vmware/go-vcloud-director/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/govcd/query.go
  vendor/github.com/vmware/go-vcloud-director/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/govcd/vapptemplate.go
  vendor/vendor.json
Labels: size/S

#117 Enhance DNAT resource
  vcd/resource_vcd_dnat.go
  vendor/github.com/vmware/go-vcloud-director/govcd/edgegateway.go
  vendor/vendor.json
Labels: size/L
