Repository vmware/terraform-provider-vcd, pull requests merged in 2018-12, with the labels that each got.

#121 Update govcd
  vcd/resource_vcd_snat.go
  vendor/github.com/vmware/go-vcloud-director/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/govcd/query.go
  vendor/github.com/vmware/go-vcloud-director/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/govcd/uploadtask.go
  vendor/github.com/vmware/go-vcloud-director/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/types/v56/types.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#123 Update vendor
  vendor/github.com/vmware/go-vcloud-director/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/govcd/task.go
  vendor/github.com/vmware/go-vcloud-director/govcd/upload.go
  vendor/vendor.json
Labels: dependencies, size/M

#124 Update doc entry page with features in vmware-takes-ownership branch
  website/docs/index.html.markdown
Labels: documentation, size/M

#127 Fix bug which omits error when organization isn't found
  vendor/github.com/vmware/go-vcloud-director/govcd/system.go
Labels: dependencies, size/XS

#130 Update doc resource pages with features in vmware-takes-ownership branch
  website/docs/index.html.markdown
  website/docs/r/catalog_item.html.markdown
  website/docs/r/catalog_media.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/edgegateway_vpn.html.markdown
  website/docs/r/firewall_rules.html.markdown
  website/docs/r/snat.html.markdown
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/S

#131 Add catalog resource docs
  website/docs/r/catalog.html.markdown
  website/vcd.erb
Labels: documentation, size/S

#133 Add support for logging in the provider
  vcd/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#134 Updated dnat docs with changes in protocol handling
  website/docs/r/dnat.html.markdown
Labels: documentation, size/XS

#136 Polish docs for network, vApp and Org resources
  website/docs/index.html.markdown
  website/docs/r/network.html.markdown
  website/docs/r/network_direct.html.markdown
  website/docs/r/network_isolated.html.markdown
  website/docs/r/network_routed.html.markdown
  website/docs/r/vapp.html.markdown
  website/vcd.erb
Labels: documentation, size/M

#138 Add default timeout to test configuration
  vcd/config_test.go
  vcd/sample_vcd_test_config.json
Labels: size/S

#119 Fix vApp/VM provisioning guest customization initscript
  vcd/resource_vcd_vapp.go
Labels: bug, size/XS

#141 Test with org admin
  vcd/config_test.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_org_test.go
  vendor/github.com/vmware/go-vcloud-director/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/types/v56/types.go
  vendor/vendor.json
Labels: dependencies, size/XL

#142 Write changelog for the new version and fix two test issues
  CHANGELOG.md
  GNUmakefile
  vcd/config_test.go
Labels: documentation, enhancement, size/S
