Repository vmware/terraform-provider-vcd, pull requests merged in 2019-03, with the labels that each got.

#180 fix 'make vet' and resolve vet issues
  GNUmakefile
  vcd/resource_vcd_vapp_vm.go
Labels: size/XS

#184 Improve eject media resource allowing force
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_inserted_media_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/ejecttask.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/inserted_media.html.markdown
Labels: dependencies, documentation, enhancement, size/XL

#191 website: add note for direct networks
  website/docs/r/network_direct.html.markdown
Labels: documentation, size/XS

#188 New independent disk resource and attach for VM
  CHANGELOG.md
  vcd/provider.go
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_independent_disk_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  website/docs/r/independent_disk.html.markdown
  website/docs/r/vapp_vm.html.markdown
  website/vcd.erb
Labels: documentation, size/XL

#189 Pass MaxRetryTimeout to govcd on initialization
  vcd/config.go
Labels: size/XS

#194 Bump go-vcloud-director dependency to v2.1.0-beta.2
  go.mod
  go.sum
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/modules.txt
Labels: dependencies, size/M

#195 Fix multi vm issue
  vcd/resource_vcd_vapp_vm.go
Labels: size/S

#197 Review changelog pre 2.1
  website/docs/r/independent_disk.html.markdown
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_network.html.markdown
  website/source/docs/providers/vcd/r/vapp_vm.html.markdown
Labels: documentation, size/M

#196 Improve changelog
  CHANGELOG.md
Labels: size/XS

#198 Updating govcd
  go.mod
  go.sum
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/modules.txt
Labels: dependencies, size/M

#199 Cpu cores support
  CHANGELOG.md
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, enhancement, size/S

#201 Update documentation on required and supported versions
  README.md
  VERSION
  website/docs/index.html.markdown
Labels: documentation, size/XS

#203 Documentation fixes before 2.1 release
  CHANGELOG.md
  README.md
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/XS

#211 Update shared secret and remove verbose messages in tests
  vcd/resource_vcd_independent_disk_test.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/sample_vcd_test_config.json
Labels: size/XS

#212 Upgrade govcd to 2.1.1 and change vapp network parameter
  go.mod
  go.sum
  vcd/resource_vcd_vapp_network.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp_network.html.markdown
Labels: dependencies, documentation, size/S

#214 remove .go-version for build compatibility
  .go-version
Labels: size/XS

#215 Change version in website title 2.0 -> 2.1
  website/docs/index.html.markdown
Labels: documentation, size/XS
