Repository vmware/terraform-provider-vcd, pull requests merged in 2019-04, with the labels that each got.

#175 Meta data fix. Ref: issue #158
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, enhancement, size/L

#221 Add tests for multiple entities in vApp
  GNUmakefile
  scripts/runtest.sh
  vcd/resource_vcd_vapp_network_multi_test.go
  vcd/resource_vcd_vapp_raw_multi_test.go
  vcd/resource_vcd_vapp_vm_multi_test.go
Labels: size/XL

#220 Add hardware_assisted_virtualization for vcd_vapp_vm resource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_checks_test.go
  vcd/resource_vcd_vapp_vm_hw_virtualization_test.go
  vcd/resource_vcd_vapp_vm_test.go
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd_versions.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalogitem.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/extension.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/query.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/task.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapptemplate.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/util/logging.go
  vendor/modules.txt
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, size/XXL

#224 Add support for network name property in vcd_snat and vcd_dnat resources
  go.mod
  go.sum
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_snat_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/modules.txt
  website/docs/r/dnat.html.markdown
  website/docs/r/snat.html.markdown
Labels: dependencies, documentation, size/XL
