Repository vmware/terraform-provider-vcd, pull requests merged in 2019-08, with the labels that each got.

#298 Add Catalog and media item attribute metadata
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
  vcd/catalogitem.go
  vcd/config_test.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_item_test.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_catalog_media_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/extension.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/metadata.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/user.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapptemplate.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/catalog_item.html.markdown
  website/docs/r/catalog_media.html.markdown
Labels: dependencies, documentation, size/XL

#283 Add Org data source
  CHANGELOG.md
  GNUmakefile
  go.mod
  go.sum
  scripts/runtest.sh
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_org.go
  vcd/datasource_vcd_org_test.go
  vcd/provider.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_org.go
  vcd/resource_vcd_org_test.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_user_test.go
  vcd/resource_vcd_vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/modules.txt
  website/docs/d/org.html.markdown
  website/docs/r/org.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XL

#301 Add usage note in build section of README.md
  README.md
Labels: documentation, size/XS

#309 Add datasource catalog and catalog item
  .gitignore
  CHANGELOG.md
  TROUBLESHOOTING.md
  go.mod
  go.sum
  vcd/catalogitem.go
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_catalog.go
  vcd/datasource_vcd_catalog_item.go
  vcd/datasource_vcd_catalog_item_test.go
  vcd/provider.go
  vcd/resource_vcd_catalog.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_item_test.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_catalog_media_test.go
  vcd/resource_vcd_catalog_test.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_external_network.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_network.go
  vcd/resource_vcd_org.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/admincatalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminvdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/entity.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/user.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/modules.txt
  website/docs/d/catalog.html.markdown
  website/docs/d/catalog_item.html.markdown
  website/docs/r/catalog.html.markdown
  website/docs/r/catalog_item.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#310 Add update support for `network` block in `vcd_vapp_vm`, allow force guest customization
  CHANGELOG.md
  GNUmakefile
  TESTING.md
  go.mod
  go.sum
  scripts/runtest.sh
  vcd/provider_test.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_external_network.go
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_app_rule_test.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_service_monitor_test.go
  vcd/resource_vcd_lb_virtual_server_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_customization_test.go
  vcd/resource_vcd_vapp_vm_hw_virtualization_test.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  vcd/resource_vcd_vapp_vm_singlenetwork_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/externalnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, size/XXL

#317 Fix firewall rule forcenew
  CHANGELOG.md
  vcd/resource_vcd_firewall_rules.go
Labels: size/XS

#319 Add support for guest properties in `vcd_vapp` and `vcd_vapp_vm` resources
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_properties_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_properties_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/productsection.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/query.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, enhancement, size/XL
