Repository vmware/terraform-provider-vcd, pull requests merged in 2019-12, with the labels that each got.

#401 Resource and data source `vcd_edgegateway` add network support for multiple subnets, sub-allocated pools and rate limits
  CHANGELOG.md
  vcd/datasource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_ipset.go
  vcd/structure.go
  website/docs/r/edgegateway.html.markdown
Labels: dependencies, documentation, size/XXL

#411 Add support for IP sets in NSX-V firewall rule
  CHANGELOG.md
  vcd/datasource_vcd_nsxv_firewall.go
  vcd/datasource_vcd_vapp_vm_test.go
  vcd/provider.go
  vcd/resource_vcd_ipset.go
  vcd/resource_vcd_ipset_test.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  website/docs/d/ipset.html.markdown
  website/docs/r/ipset.html.markdown
  website/docs/r/nsxv_firewall_rule.markdown
  website/vcd.erb
Labels: documentation, enhancement, size/XL

#416 Add Edge Gateway DHCP relay configuration support
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_nsxv_dhcp_relay.go
  vcd/provider.go
  vcd/resource_vcd_nsxv_dhcp_relay.go
  vcd/resource_vcd_nsxv_dhcp_relay_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/nsxv_dhcprelay.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/nsxv_types.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/nsxv_dhcp_relay.markdown
  website/docs/r/nsxv_dhcp_relay.markdown
  website/vcd.erb
Labels: dependencies, documentation, enhancement, size/XXL

#414 Do not send fips_mode_enabled when it is not set (needed for vCD 9.0)
  CHANGELOG.md
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  website/docs/r/edgegateway.html.markdown
Labels: bug, documentation, size/S

#418 vCD 9.0 testing bugfixes
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_ipset.go
  vcd/resource_vcd_nsxv_dhcp_relay.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vendor/modules.txt
  website/docs/r/edgegateway.html.markdown
Labels: bug, dependencies, documentation, size/L

#419 Fix an issue where vcd_nsxv_firewall_rule and vcd_nsxv_dnat may fail using a regular user
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config_test.go
  vcd/datasource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/modules.txt
  website/docs/r/edgegateway.html.markdown
Labels: dependencies, documentation, size/S

#422 Fix documentation formatting
  website/docs/index.html.markdown
Labels: documentation, size/XS
