Repository vmware/terraform-provider-vcd, pull requests merged in 2019-02, with the labels that each got.

#156 issue #65 documentation change firewall default_action deny to drop
  website/docs/r/firewall_rules.html.markdown
Labels: documentation, size/XS

#163 Vmware stash branch update with Master branch changes
  CHANGELOG.md
  GNUmakefile
  README.md
  ResourceExamples/vcd_test.tf
  VERSION
  scripts/install-plugin.sh
  vcd/catalogitem.go
  vcd/config.go
  vcd/config_test.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_catalog.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_item_test.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_catalog_media_test.go
  vcd/resource_vcd_catalog_test.go
  vcd/resource_vcd_edgegateway_vpn.go
  vcd/resource_vcd_edgegateway_vpn_test.go
  vcd/resource_vcd_firewall_rules_test.go
  vcd/resource_vcd_network.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_org.go
  vcd/resource_vcd_org_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/structure.go
  website/docs/index.html.markdown
  website/docs/r/catalog.html.markdown
  website/docs/r/catalog_item.html.markdown
  website/docs/r/catalog_media.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/edgegateway_vpn.html.markdown
  website/docs/r/firewall_rules.html.markdown
  website/docs/r/network_direct.html.markdown
  website/docs/r/network_isolated.html.markdown
  website/docs/r/network_routed.html.markdown
  website/docs/r/org.html.markdown
  website/docs/r/snat.html.markdown
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/XL

#166 Improve generation of test snippets
  GNUmakefile
  README.md
  TESTING.md
  vcd/config_test.go
  vcd/sample_vcd_test_config.json
Labels: size/L

#155 Add vapp network resource
  vcd/config_test.go
  vcd/provider.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_vm.go
  vendor/github.com/vmware/go-vcloud-director/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/govcd/task.go
  vendor/github.com/vmware/go-vcloud-director/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/types/v56/types.go
  vendor/vendor.json
  website/docs/r/vapp_network.html.markdown
  website/docs/r/vapp_vm.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL
