Repository vmware/terraform-provider-vcd, pull requests merged in 2019-06, with the labels that each got.

#255 Mutex change
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_edgegateway_vpn.go
  vcd/resource_vcd_firewall_rules.go
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_multi_test.go
  vcd/resource_vcd_vapp_raw_multi_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_checks_test.go
  vcd/resource_vcd_vapp_vm_multi_test.go
  vcd/resource_vcd_vapp_vm_test.go
  vendor/github.com/hashicorp/terraform/helper/mutexkv/mutexkv.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#256 Add load balancer service monitor resource and datasource
  .gitignore
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_lb_service_monitor.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_firewall_rules_test.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_lb_service_monitor_test.go
  vcd/test-templates/load-balancer1.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/monitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/task.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/lb_service_monitor.html.markdown
  website/docs/r/lb_service_monitor.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#263 Edge gateway creation
  CHANGELOG.md
  GNUmakefile
  TESTING.md
  VERSION
  scripts/runtest.sh
  scripts/test-binary.sh
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_lb_service_monitor.go
  vcd/provider.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_edgegateway_vpn.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_firewall_rules.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_snat.go
  vcd/sample_vcd_test_config.json
  vcd/terraform_binary_test.go
  vcd/test-templates/full-env.tf
  website/docs/index.html.markdown
  website/docs/r/edgegateway.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#261 fix typo that undeploys vapp instead of vm while deleting a vm
  vcd/resource_vcd_vapp_vm.go
Labels: size/S

#272 Update independent disk size type
  go.mod
  go.sum
  vcd/resource_vcd_independent_disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
Labels: dependencies, size/XS
