Repository vmware/terraform-provider-vcd, pull requests merged in 2019-11, with the labels that each got.

#380 Vdc datasource crash fix
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_org_vdc_test.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/org_vdc.html.markdown
  website/docs/r/org_vdc.html.markdown
Labels: dependencies, documentation, size/L

#384 Fix minor problems in NSX-V related resources
  CHANGELOG.md
  VERSION
  vcd/datasource_vcd_nsxv_dnat.go
  vcd/datasource_vcd_nsxv_firewall.go
  vcd/datasource_vcd_nsxv_snat.go
  vcd/nsxv_nat.go
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_nsxv_dnat.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vcd/resource_vcd_nsxv_snat.go
  vcd/suppress_funcs.go
  vcd/validate_funcs.go
  website/docs/index.html.markdown
  website/docs/r/nsxv_dnat.html.markdown
Labels: documentation, enhancement, size/L

#386 Add vm datasource and import
  CHANGELOG.md
  go.mod
  go.sum
  scripts/test-binary.sh
  vcd/datasource_vcd_vapp.go
  vcd/datasource_vcd_vapp_test.go
  vcd/datasource_vcd_vapp_vm.go
  vcd/datasource_vcd_vapp_vm_test.go
  vcd/provider.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  vcd/validate_funcs.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/metadata.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/user.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapptemplate.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/modules.txt
  website/docs/d/vapp.html.markdown
  website/docs/d/vapp_vm.html.markdown
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_vm.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#356 Fix filtering
  go.mod
  go.sum
  vcd/resource_vcd_org_vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/modules.txt
Labels: dependencies, size/S

#390 Enable staticcheck
  .travis.yml
  CHANGELOG.md
  GNUmakefile
  scripts/runtest.sh
  scripts/staticcheck-config.sh
  vcd/api_test.go
  vcd/catalogitem.go
  vcd/provider_unit_test.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_firewall_rules.go
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_snat_test.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vcd/structure.go
  vcd/suppress_funcs.go
  vcd/validate_funcs.go
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/L

#389 Add `default_external_network_ip` computed field to resource and data source `vcd_edge_gateway`
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/github.com/vmware/go-vcloud-director/v2/util/logging.go
  vendor/github.com/vmware/go-vcloud-director/v2/util/tar.go
  vendor/modules.txt
  website/docs/r/edgegateway.html.markdown
  website/docs/r/lb_virtual_server.html.markdown
  website/docs/r/nsxv_firewall_rule.markdown
Labels: dependencies, documentation, size/M

#393 Add ability of using authorization tokens
  CHANGELOG.md
  GNUmakefile
  TESTING.md
  go.mod
  go.sum
  scripts/get_token.sh
  scripts/runtest.sh
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_network_test.go
  vcd/datasource_vcd_vapp_test.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/sample_vcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/XL

#394 Independent disk fix
  CHANGELOG.md
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_independent_disk_test.go
Labels: size/S

#396 Increment vCD API version from 27.0 to 29.0
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
Labels: dependencies, size/M

#400 Upgrade tests
  CHANGELOG.md
  GNUmakefile
  PREVIOUS_VERSION
  TESTING.md
  go.mod
  scripts/skip-upgrade-tests.txt
  scripts/test-binary.sh
  scripts/test-upgrade.sh
  vcd/api_test.go
  vcd/datasource_vcd_catalog_item_test.go
  vcd/datasource_vcd_catalog_media_test.go
  vcd/datasource_vcd_independent_disk_test.go
  vcd/datasource_vcd_org_test.go
  vcd/datasource_vcd_org_vdc_test.go
  vcd/provider_unit_test.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_app_rule_test.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_service_monitor_test.go
  vcd/resource_vcd_lb_virtual_server_test.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_nsxv_dnat_test.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vcd/resource_vcd_nsxv_snat_test.go
  vcd/resource_vcd_org_user_test.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_multi_test.go
  vcd/resource_vcd_vapp_raw_multi_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm_customization_test.go
  vcd/resource_vcd_vapp_vm_hw_virtualization_test.go
  vcd/resource_vcd_vapp_vm_multi_test.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  vcd/resource_vcd_vapp_vm_properties_test.go
  vcd/resource_vcd_vapp_vm_singlenetwork_test.go
  vcd/resource_vcd_vapp_vm_test.go
  vcd/terraform_binary_test.go
  vcd/test-templates/full-env.tf
Labels: size/XL

#402 Add property "interface_type" and improve networks
  CHANGELOG.md
  TESTING.md
  go.mod
  go.sum
  vcd/datasource_vcd_network_direct.go
  vcd/datasource_vcd_network_isolated.go
  vcd/datasource_vcd_network_routed.go
  vcd/datasource_vcd_network_test.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_vapp_network.go
  vcd/structure.go
  vcd/suppress_funcs.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbvirtualserver.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/network_direct.html.markdown
  website/docs/r/network_isolated.html.markdown
  website/docs/r/network_routed.html.markdown
Labels: dependencies, documentation, size/XL

#408 Enable org users to see direct network data
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_network_test.go
  vcd/resource_vcd_network_direct.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
Labels: dependencies, size/M
