Repository vmware/terraform-provider-vcd, pull requests merged in 2019-07, with the labels that each got.

#268 Add load balancer server pool resource and datasource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config_test.go
  vcd/datasource_vcd_lb_server_pool.go
  vcd/datasource_vcd_lb_service_monitor.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/test-templates/load-balancer1.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/lb_server_pool.markdown
  website/docs/d/lb_service_monitor.html.markdown
  website/docs/r/lb_server_pool.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#275 Vdc update
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/metadata.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/org_vdc.html.markdown
Labels: dependencies, documentation, size/XL

#274 Add load balancer application profile resource and data source
  CHANGELOG.md
  go.mod
  go.sum
  vcd/api_test.go
  vcd/datasource_vcd_lb_app_profile.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_lb_app_profile.go
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/test-templates/load-balancer1.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lb.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbappprofile.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/monitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/user.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/lb_app_profile.html.markdown
  website/docs/d/lb_server_pool.markdown
  website/docs/d/lb_service_monitor.html.markdown
  website/docs/r/lb_app_profile.html.markdown
  website/docs/r/lb_server_pool.html.markdown
  website/docs/r/lb_service_monitor.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, enhancement, size/XXL

#277 Add VDC metadata functionality
  CHANGELOG.md
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  website/docs/r/org_vdc.html.markdown
Labels: documentation, size/M

#279 Add org user
  CHANGELOG.md
  GNUmakefile
  TESTING.md
  go.mod
  go.sum
  scripts/runtest.sh
  scripts/test-binary.sh
  vcd/api_test.go
  vcd/config_test.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_user_test.go
  vcd/sample_vcd_test_config.json
  vcd/terraform_binary_test.go
  vcd/test-templates/full-env.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/user.go
  vendor/modules.txt
  website/docs/r/org_user.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XL

#278 Add load balancer application rule resource and data source
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_lb_app_profile.go
  vcd/datasource_vcd_lb_app_rule.go
  vcd/datasource_vcd_lb_server_pool.go
  vcd/datasource_vcd_lb_service_monitor.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_lb_app_profile.go
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_app_rule.go
  vcd/resource_vcd_lb_app_rule_test.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_lb_service_monitor_test.go
  vcd/test-templates/load-balancer1.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lb.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbappprofile.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbapprule.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/lb_app_profile.html.markdown
  website/docs/d/lb_app_rule.html.markdown
  website/docs/d/lb_server_pool.markdown
  website/docs/d/lb_service_monitor.html.markdown
  website/docs/r/lb_app_rule.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#282 NAT rule support IDs and external or Org networks
  CHANGELOG.md
  go.mod
  go.sum
  scripts/runtest.sh
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_snat_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/modules.txt
  website/docs/r/dnat.html.markdown
  website/docs/r/snat.html.markdown
Labels: dependencies, documentation, size/XXL

#286 Improve tests
  scripts/runtest.sh
  scripts/test-binary.sh
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_snat_test.go
Labels: size/XS

#284 Add load balancer virtual server resource and data source
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_lb_virtual_server.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_lb_app_rule_test.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_virtual_server.go
  vcd/resource_vcd_lb_virtual_server_test.go
  vcd/test-templates/load-balancer1.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbvirtualserver.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/lb_virtual_server.html.markdown
  website/docs/r/lb_virtual_server.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#288 Add load balancing configuration for edge gateway
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/edgegateway.html.markdown
Labels: dependencies, documentation, size/XL

#290 Load balancer syntax cleanup and bugfixes
  go.mod
  go.sum
  vcd/datasource_vcd_lb_app_profile.go
  vcd/datasource_vcd_lb_app_rule.go
  vcd/datasource_vcd_lb_server_pool.go
  vcd/datasource_vcd_lb_service_monitor.go
  vcd/datasource_vcd_lb_virtual_server.go
  vcd/resource_vcd_lb_app_profile.go
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_app_rule.go
  vcd/resource_vcd_lb_app_rule_test.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_lb_service_monitor_test.go
  vcd/resource_vcd_lb_virtual_server.go
  vcd/resource_vcd_lb_virtual_server_test.go
  vcd/resource_vcd_org_user.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd_versions.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lb.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbappprofile.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbapprule.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbvirtualserver.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/lb_app_profile.html.markdown
  website/docs/r/lb_app_rule.html.markdown
  website/docs/r/lb_server_pool.html.markdown
  website/docs/r/lb_service_monitor.html.markdown
Labels: dependencies, documentation, size/XXL

#291 Bump go-vcloud-director dependency to v2.3.0-rc.2
  go.mod
  go.sum
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbappprofile.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbapprule.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbserverpool.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbservicemonitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/lbvirtualserver.go
  vendor/modules.txt
Labels: dependencies, size/S

#292 Add fixes for DNAT
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_snat_test.go
Labels: size/S

#293 Fix for protocol upper/lower case handling
  CHANGELOG.md
  go.mod
  go.sum
  v2Plan.md
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/snat.html.markdown
Labels: dependencies, documentation, size/L

#295 Documentation inconsistency: load balancer service monitor field 'extension' is optional
  website/docs/r/lb_service_monitor.html.markdown
Labels: documentation, size/XS

#297 Improve tests for load balancer boolean fields and bump govcd dependency
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_virtual_server_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
Labels: dependencies, size/M
