Repository vmware/terraform-provider-vcd, pull requests merged in 2019-05, with the labels that each got.

#226 Add tags to all test files
  CHANGELOG.md
  GNUmakefile
  TESTING.md
  scripts/runtest.sh
  vcd/api_test.go
  vcd/config_test.go
  vcd/provider_test.go
  vcd/resource_vcd_catalog_item_test.go
  vcd/resource_vcd_catalog_media_test.go
  vcd/resource_vcd_catalog_test.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_edgegateway_vpn_test.go
  vcd/resource_vcd_firewall_rules_test.go
  vcd/resource_vcd_independent_disk_test.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_org_test.go
  vcd/resource_vcd_snat_test.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm_checks_test.go
  vcd/resource_vcd_vapp_vm_hw_virtualization_test.go
  vcd/resource_vcd_vapp_vm_test.go
Labels: size/XL

#230 Add external network resource
  CHANGELOG.md
  GNUmakefile
  TESTING.md
  go.mod
  go.sum
  scripts/runtest.sh
  vcd/config_test.go
  vcd/provider.go
  vcd/provider_test.go
  vcd/resource_vcd_external_network.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/sample_vcd_test_config.json
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/extension.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/externalnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/external_network.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#233 Multiple networks support in vcd_vapp_vm resource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  vcd/resource_vcd_vapp_vm_singlenetwork_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, size/XXL

#236 Add VdC resource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config.go
  vcd/config_test.go
  vcd/provider.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/sample_vcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/org_vdc.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XL

#240 Added check for existing org VDC in Org VDC resource
  vcd/resource_vcd_org_vdc.go
Labels: size/XS

#242 Fix error in documentation
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/XS

#243 Fix typo in vcd_vapp_vm website example
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/XS

#241 Improve documentation for allocation models
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/org_vdc.html.markdown
Labels: dependencies, documentation, size/L

#245 Fix snat read bug and introduced network_type
  CHANGELOG.md
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_snat_test.go
  vcd/resource_vcd_vapp_network.go
  website/docs/r/dnat.html.markdown
  website/docs/r/snat.html.markdown
Labels: documentation, size/M

#246 Remove new attributes from DNAT/SNAT
  CHANGELOG.md
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_snat.go
  website/docs/r/dnat.html.markdown
  website/docs/r/snat.html.markdown
Labels: documentation, size/XS

#247 Change website title to 2.2
  website/docs/index.html.markdown
Labels: documentation, size/XS

#249 add missing depends_on, proper step names to TestAccVcdVAppVmSingleNIC
  vcd/resource_vcd_vapp_vm_singlenetwork_test.go
Labels: size/XS

#248 Add check for version in docs header
  GNUmakefile
  TESTING.md
  scripts/runtest.sh
  vcd/api_test.go
  vcd/config_test.go
  vcd/provider_unit_test.go
Labels: size/XL

#251 Implement Issue #250 Terraform binary tests
  GNUmakefile
  TESTING.md
  scripts/runtest.sh
  scripts/test-binary.sh
  vcd/api_test.go
  vcd/config_test.go
  vcd/resource_vcd_catalog_item_test.go
  vcd/resource_vcd_catalog_media_test.go
  vcd/resource_vcd_catalog_test.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_edgegateway_vpn_test.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_firewall_rules_test.go
  vcd/resource_vcd_independent_disk_test.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_org_test.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_snat_test.go
  vcd/resource_vcd_vapp_network_multi_test.go
  vcd/resource_vcd_vapp_raw_multi_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm_hw_virtualization_test.go
  vcd/resource_vcd_vapp_vm_multi_test.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  vcd/resource_vcd_vapp_vm_singlenetwork_test.go
  vcd/resource_vcd_vapp_vm_test.go
Labels: size/XL
