Repository vmware/terraform-provider-vcd, pull requests merged in 2019-09, with the labels that each got.

#322 Add datasource external-network
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_external_network.go
  vcd/provider.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_external_network.go
  vcd/resource_vcd_external_network_test.go
  website/docs/d/external_network.html.markdown
  website/docs/r/external_network.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XL

#324 Org VDC import, data source and read fix
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config_test.go
  vcd/datasource_vcd_org_vdc.go
  vcd/datasource_vcd_org_vdc_test.go
  vcd/provider.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/github.com/vmware/go-vcloud-director/v2/util/tar.go
  vendor/modules.txt
  website/docs/d/org_vdc.html.markdown
  website/docs/r/org_vdc.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#328 Add `vcd_nsxv_dnat` and `vcd_nsxv_snat` resources and data sources
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_catalog.go
  vcd/datasource_vcd_catalog_item.go
  vcd/datasource_vcd_lb_app_profile.go
  vcd/datasource_vcd_lb_app_rule.go
  vcd/datasource_vcd_lb_server_pool.go
  vcd/datasource_vcd_lb_service_monitor.go
  vcd/datasource_vcd_lb_virtual_server.go
  vcd/datasource_vcd_nsxv_dnat.go
  vcd/datasource_vcd_nsxv_snat.go
  vcd/nsxv_nat.go
  vcd/provider.go
  vcd/resource_vcd_catalog.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_edgegateway_vpn.go
  vcd/resource_vcd_firewall_rules.go
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_lb_app_profile.go
  vcd/resource_vcd_lb_app_rule.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_lb_virtual_server.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_nsxv_dnat.go
  vcd/resource_vcd_nsxv_dnat_test.go
  vcd/resource_vcd_nsxv_snat.go
  vcd/resource_vcd_nsxv_snat_test.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_vm.go
  vcd/suppressfuncs.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/nat.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/nsxv_dnat.html.markdown
  website/docs/d/nsxv_snat.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/lb_app_rule.html.markdown
  website/docs/r/nsxv_dnat.html.markdown
  website/docs/r/nsxv_snat.html.markdown
  website/docs/r/snat.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#334 Computername fix
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_snat.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  vcd/suppressfuncs.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/modules.txt
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, size/XL

#333 Add datasource for networks and edge gateway
  CHANGELOG.md
  TROUBLESHOOTING.md
  vcd/config.go
  vcd/datasource_vcd_edgegateway.go
  vcd/datasource_vcd_network_direct.go
  vcd/datasource_vcd_network_isolated.go
  vcd/datasource_vcd_network_routed.go
  vcd/datasource_vcd_network_test.go
  vcd/datasource_vcd_org_test.go
  vcd/datasource_vcd_org_vdc_test.go
  vcd/nsxv_nat.go
  vcd/provider.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_firewall_rules_test.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_lb_virtual_server.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_snat_test.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_vm.go
  vcd/suppressfuncs.go
  website/docs/d/edgegateway.html.markdown
  website/docs/d/network_direct.html.markdown
  website/docs/d/network_isolated.html.markdown
  website/docs/d/network_routed.html.markdown
  website/docs/r/edgegateway.html.markdown
  website/docs/r/network_direct.html.markdown
  website/docs/r/network_isolated.html.markdown
  website/docs/r/network_routed.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#337 Replace usage of deprecated functions
  vcd/resource_vcd_inserted_media.go
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_multi_test.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_raw_multi_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_checks_test.go
  vcd/resource_vcd_vapp_vm_customization_test.go
  vcd/resource_vcd_vapp_vm_multi_test.go
Labels: size/L
