Repository vmware/terraform-provider-vcd, pull requests merged in 2019-10, with the labels that each got.

#339 Add vcd_vapp datasource and importing
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config_test.go
  vcd/datasource_vcd_network_test.go
  vcd/datasource_vcd_vapp.go
  vcd/datasource_vcd_vapp_test.go
  vcd/provider.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_test.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_external_network_test.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_org_test.go
  vcd/resource_vcd_org_user_test.go
  vcd/resource_vcd_vapp.go
  vcd/resource_vcd_vapp_test.go
  vcd/resource_vcd_vapp_vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/modules.txt
  website/docs/d/vapp.html.markdown
  website/docs/r/vapp.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XL

#353 Add dynamic separator for terraform import
  CHANGELOG.md
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_catalog_item_test.go
  vcd/nsxv_nat.go
  vcd/provider.go
  vcd/resource_vcd_catalog.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_lb_app_profile.go
  vcd/resource_vcd_lb_app_rule.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_lb_virtual_server.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_nsxv_dnat_test.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_vapp.go
  website/docs/index.html.markdown
  website/docs/r/catalog.html.markdown
  website/docs/r/catalog_item.html.markdown
  website/docs/r/edgegateway.html.markdown
  website/docs/r/external_network.html.markdown
  website/docs/r/network_direct.html.markdown
  website/docs/r/network_isolated.html.markdown
  website/docs/r/network_routed.html.markdown
  website/docs/r/nsxv_dnat.html.markdown
  website/docs/r/nsxv_snat.html.markdown
  website/docs/r/org_user.html.markdown
  website/docs/r/org_vdc.html.markdown
  website/docs/r/vapp.html.markdown
Labels: documentation, size/L

#340 Add Media datasource/import and enhanced read
  CHANGELOG.md
  go.mod
  go.sum
  vcd/catalogitem.go
  vcd/datasource_vcd_catalog_item_test.go
  vcd/datasource_vcd_catalog_media.go
  vcd/datasource_vcd_catalog_media_test.go
  vcd/provider.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_catalog_media_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/metadata.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/catalog_media.html.markdown
  website/docs/r/catalog_media.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#354 Fix docs and rename import separator variable
  CHANGELOG.md
  vcd/config.go
  vcd/config_test.go
  vcd/nsxv_nat.go
  vcd/provider.go
  vcd/resource_vcd_catalog.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_lb_app_profile.go
  vcd/resource_vcd_lb_app_rule.go
  vcd/resource_vcd_lb_server_pool.go
  vcd/resource_vcd_lb_service_monitor.go
  vcd/resource_vcd_lb_virtual_server.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_nsxv_dnat_test.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_vapp.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#349 Add independent disk datasource
  CHANGELOG.md
  vcd/datasource_vcd_independent_disk.go
  vcd/datasource_vcd_independent_disk_test.go
  vcd/datasource_vcd_org_vdc_test.go
  vcd/provider.go
  vcd/resource_vcd_independent_disk.go
  vcd/resource_vcd_independent_disk_test.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_vapp_vm.go
  website/docs/d/independent_disk.html.markdown
  website/docs/r/independent_disk.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XL

#341 Add vcd_nsxv_firewall_rule resource and data source for advanced edge gateways
  CHANGELOG.md
  CODING_GUIDELINES.md
  README.md
  vcd/datasource_vcd_edgegateway.go
  vcd/datasource_vcd_nsxv_firewall.go
  vcd/provider.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_lb_app_profile_test.go
  vcd/resource_vcd_lb_app_rule_test.go
  vcd/resource_vcd_lb_server_pool_test.go
  vcd/resource_vcd_lb_service_monitor_test.go
  vcd/resource_vcd_lb_virtual_server_test.go
  vcd/resource_vcd_nsxv_dnat_test.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vcd/resource_vcd_nsxv_snat_test.go
  vcd/structure.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/nsxv_firewall.go
  website/docs/d/nsxv_firewall_rule.html.markdown
  website/docs/r/edgegateway.html.markdown
  website/docs/r/firewall_rules.html.markdown
  website/docs/r/nsxv_firewall_rule.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#357 Comment out leftovers
  vcd/resource_vcd_independent_disk_test.go
Labels: size/XS

#358 Address outstanding issues before the release
  CHANGELOG.md
  TROUBLESHOOTING.md
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  website/docs/r/firewall_rules.html.markdown
  website/docs/r/nsxv_dnat.html.markdown
  website/docs/r/nsxv_snat.html.markdown
Labels: documentation, size/L

#359 Improve handling of "org" field in User resource
  vcd/resource_vcd_org_user.go
Labels: size/XS

#360 Fix independent disk bus su type and storage profile read
  vcd/resource_vcd_independent_disk.go
  website/docs/r/independent_disk.html.markdown
Labels: documentation, size/XS

#363 Fix Org resource and datasource
  go.mod
  go.sum
  vcd/datasource_vcd_org.go
  vcd/datasource_vcd_org_test.go
  vcd/resource_vcd_org.go
  vcd/resource_vcd_org_user.go
  vcd/resource_vcd_org_user_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/user.go
  vendor/modules.txt
Labels: dependencies, size/S

#361 Add extra step in binary tests to ensure plan is stable, fix `shared_secret` in vcd_edgegateway_vpn
  CHANGELOG.md
  TESTING.md
  scripts/test-binary.sh
  vcd/resource_vcd_edgegateway_vpn.go
  vcd/resource_vcd_edgegateway_vpn_test.go
  vcd/test-templates/misc2.tf
Labels: size/S

#383 Add Env variable to enable Org user tests
  GNUmakefile
  TESTING.md
  scripts/runtest.sh
  vcd/config_test.go
  vcd/datasource_vcd_independent_disk_test.go
  vcd/resource_vcd_dnat_test.go
  vcd/resource_vcd_independent_disk_test.go
Labels: size/M
