Repository vmware/terraform-provider-vcd, pull requests merged in 2020-03, with the labels that each got.

#455 Add vApp network resources and data sources
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_test.go
  vcd/datasource_vcd_vapp_network.go
  vcd/datasource_vcd_vapp_network_test.go
  vcd/datasource_vcd_vapp_org_network.go
  vcd/datasource_vcd_vapp_org_network_test.go
  vcd/datasource_vcd_vapp_vm.go
  vcd/provider.go
  vcd/resource_vcd_external_network.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_org_network.go
  vcd/resource_vcd_vapp_org_network_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_singlenetwork_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/nsxv_ipset.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/vapp_network.html.markdown
  website/docs/d/vapp_org_network.html.markdown
  website/docs/r/vapp_network.html.markdown
  website/docs/r/vapp_org_network.html.markdown
  website/docs/r/vapp_vm.html.markdown
  website/docs/r/vm_internal_disk.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#462 Add support for all Guest Customization options in resource and data source `vcd_vapp_vm`
  CHANGELOG.md
  GNUmakefile
  go.mod
  go.sum
  scripts/skip-upgrade-tests.txt
  vcd/datasource_vcd_network_test.go
  vcd/datasource_vcd_vapp_org_network_test.go
  vcd/datasource_vcd_vapp_vm.go
  vcd/datasource_vcd_vapp_vm_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_customization_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp_vm.html.markdown
Labels: bug, dependencies, documentation, enhancement, size/XL

#468 vApp network test changed to be independent from existing vapp
  vcd/datasource_vcd_vapp_network_test.go
  vcd/datasource_vcd_vapp_org_network_test.go
Labels: size/S

#469 Make datasource vcd_vapp_vm test predictable
  vcd/datasource_vcd_vapp_vm_test.go
Labels: bug, size/M

#467 Cleanup CHANGELOG and docs for 2.7 release
  CHANGELOG.md
  website/docs/r/vapp.html.markdown
  website/docs/r/vapp_network.html.markdown
Labels: documentation, size/M

#470 Skip TestAccDataSourceNotFound/vcd_external_network test with org user
  CHANGELOG.md
  vcd/datasource_test.go
Labels: size/XS

#472 Improved VM network to allow reference vApp routed network
  CHANGELOG.md
  vcd/datasource_vcd_org_vdc_test.go
  vcd/datasource_vcd_vapp_network_test.go
  vcd/datasource_vcd_vapp_org_network_test.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_org_network.go
  vcd/resource_vcd_vapp_org_network_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
Labels: size/L

#475 Fix issue were vCD 9.1 version doesn't have property description in vapp network
  vcd/resource_vcd_vapp_network_test.go
  website/docs/r/vapp_network.html.markdown
Labels: documentation, size/XS

#476 Add recovery feature to binary tests
  TESTING.md
  scripts/runtest.sh
  scripts/test-binary.sh
Labels: size/L

#477 Add NIC to VM in test 'TestAccVcdVAppVmUpdateCustomization'
  CHANGELOG.md
  go.mod
  go.sum
  vcd/resource_vcd_vapp_vm_customization_test.go
  vendor/modules.txt
Labels: dependencies, size/S

#465 Update networks
  CHANGELOG.md
  PREVIOUS_VERSION
  VERSION
  go.mod
  go.sum
  scripts/skip-upgrade-tests.txt
  scripts/test-binary.sh
  vcd/api_test.go
  vcd/datasource_vcd_network_isolated.go
  vcd/datasource_vcd_network_routed.go
  vcd/datasource_vcd_network_test.go
  vcd/datasource_vcd_vapp_network.go
  vcd/resource_vcd_network_direct.go
  vcd/resource_vcd_network_isolated.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_org_network_test.go
  vcd/suppress_funcs.go
  vcd/test-templates/full-env.tf
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/monitor.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/network_isolated.html.markdown
  website/docs/r/network_routed.html.markdown
Labels: dependencies, documentation, size/XXL

#481 Add import documentation for vApp networks
  CHANGELOG.md
  website/docs/r/vapp_network.html.markdown
  website/docs/r/vapp_org_network.html.markdown
Labels: documentation, size/S

#478 Fix deprecated 'ip' and 'mac' read for legacy `vcd_vapp_vm` resource
  CHANGELOG.md
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_unit_test.go
Labels: size/XL
