Repository vmware/terraform-provider-vcd, pull requests merged in 2020-05, with the labels that each got.

#501 Added possibility to choose VM in multi vApp template
  CHANGELOG.md
  go.mod
  go.sum
  test-resources/vapp_with_3_vms.ova
  vcd/config_test.go
  vcd/resource_vcd_vapp_multi_vm_in_template_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/sample_vcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/sample_govcd_test_config.yaml
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/modules.txt
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, size/XL

#505 Add command line flags for tests
  CHANGELOG.md
  TESTING.md
  vcd/api_test.go
  vcd/config_test.go
  vcd/provider_unit_test.go
  vcd/resource_vcd_network_test.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
Labels: size/M

#512 Fix incorrect vcd_vapp_vm 'network.x.is_primary' read when vCD NIC starts with index != 0
  CHANGELOG.md
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
Labels: dependencies, size/L
