Repository vmware/terraform-provider-vcd, pull requests merged in 2020-01, with the labels that each got.

#426 Declare vCD 9.0 support drop
  CHANGELOG.md
  website/docs/index.html.markdown
Labels: documentation, size/XS

#412 Vm disk feature
  CHANGELOG.md
  PREVIOUS_VERSION
  VERSION
  go.mod
  go.sum
  vcd/config.go
  vcd/config_test.go
  vcd/datasource_vcd_vapp_vm.go
  vcd/provider.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_independent_disk_test.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  vcd/resource_vcd_vm_internal_disk.go
  vcd/resource_vcd_vm_internal_disk_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd_versions.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/github.com/vmware/go-vcloud-director/v2/util/logging.go
  vendor/modules.txt
  website/docs/d/org_vdc.html.markdown
  website/docs/d/vapp_vm.html.markdown
  website/docs/index.html.markdown
  website/docs/r/independent_disk.html.markdown
  website/docs/r/vapp_vm.html.markdown
  website/docs/r/vm_internal_disk.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#433 Fix independent disk refresh losing bus_number and unit_number values
  CHANGELOG.md
  vcd/datasource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_test.go
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/M

#432 Add section vapp_lease and vapp_template_lease
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_org.go
  vcd/datasource_vcd_org_test.go
  vcd/resource_vcd_org.go
  vcd/resource_vcd_org_test.go
  vcd/validate_funcs.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/org.html.markdown
  website/docs/r/org.html.markdown
Labels: dependencies, documentation, size/XL
