Repository vmware/terraform-provider-vcd, pull requests merged in 2020-04, with the labels that each got.

#485 `vcd_vapp_vm` - do not check for None network records in vApp when used with `dhcp_wait_seconds`
  CHANGELOG.md
  scripts/skip-upgrade-tests.txt
  vcd/resource_vcd_vapp_vm.go
Labels: size/XS

#489 Pull in latest go-vcloud-director SDK with 10.1 fixes
  CHANGELOG.md
  go.mod
  go.sum
  scripts/skip-upgrade-tests.txt
  scripts/test-binary.sh
  vcd/config.go
  vcd/resource_vcd_vapp_vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminvdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd_versions.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/disk.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/query.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/L

#494 Add vCD 10.1 `vcd_org_vdc` fix note to changelog
  CHANGELOG.md
Labels: size/XS

#496 Improve GitHub issue template by adding debug configuration steps
  .github/ISSUE_TEMPLATE.md
Labels: size/XS

#492 Increase API version
  CHANGELOG.md
  PREVIOUS_VERSION
  VERSION
  go.mod
  go.sum
  vcd/resource_vcd_edgegateway_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/M

#484 Allows to create empty VM
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config_test.go
  vcd/resource_vcd_vapp_emtpy_vm_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/sample_vcd_test_config.json
  vcd/structure.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/vm_types.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, size/XXL

#498 Improve tests
  vcd/resource_vcd_inserted_media_test.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vcd/resource_vcd_vapp_raw_test.go
  vcd/resource_vcd_vapp_vm_dhcp_wait_test.go
  vcd/resource_vcd_vapp_vm_multi_test.go
  vcd/resource_vcd_vapp_vm_test.go
Labels: size/M

#499 Cleanup after api increase
  CHANGELOG.md
  go.mod
  go.sum
  scripts/get_token.sh
  scripts/runtest.sh
  vcd/datasource_vcd_org_vdc.go
  vcd/datasource_vcd_org_vdc_test.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_edgegateway_test.go
  vcd/resource_vcd_nsxv_firewall_rule.go
  vcd/resource_vcd_nsxv_firewall_rule_test.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vcd/resource_vcd_vapp_network_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminvdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/edgegateway.html.markdown
  website/docs/r/vapp_network.html.markdown
Labels: dependencies, documentation, size/L
