Repository vmware/terraform-provider-vcd, pull requests merged in 2020-07, with the labels that each got.

#532 Improve isolation of tagged tests
  CHANGELOG.md
  GNUmakefile
  scripts/test-tags.sh
  vcd/config_test.go
  vcd/datasource_vcd_org_vdc_test.go
Labels: size/M

#534 Changelog automation
  .changes/README.md
  .changes/sections
  .changes/v2.10.0/532-improvements.md
  .changes/v2.10.0/534-improvements.md
  .changes/v2.9.0/484-improvements.md
  .changes/v2.9.0/487-improvements.md
  .changes/v2.9.0/492-notes.md
  .changes/v2.9.0/499-improvements.md
  .changes/v2.9.0/501-improvements.md
  .changes/v2.9.0/504-features.md
  .changes/v2.9.0/505-improvements.md
  .changes/v2.9.0/511-bug-fixes.md
  .changes/v2.9.0/511-features.md
  .changes/v2.9.0/512-bug-fixes.md
  .changes/v2.9.0/513-features.md
  .changes/v2.9.0/514-features.md
  .changes/v2.9.0/518-deprecations.md
  .changes/v2.9.0/518-features.md
  .changes/v2.9.0/520-features.md
  .changes/v2.9.0/522-bug-fixes.md
  CHANGELOG.md
  PREVIOUS_VERSION
  VERSION
  scripts/make-changelog.sh
  website/docs/index.html.markdown
Labels: documentation, size/M

#535 Add toggle to allow network connection turn on or off for VM network
  .changes/v2.10.0/535-improvements.md
  scripts/skip-upgrade-tests.txt
  vcd/datasource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_emtpy_vm_test.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_dhcp_wait_test.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, size/M

#538 fix allocation mode when empty VM is created
  vcd/resource_vcd_vapp_vm.go
Labels: size/XS
