Repository vmware/terraform-provider-vcd, pull requests merged in 2020-06, with the labels that each got.

#518 Deprecate resources dnat, snat, firewall_rules
  CHANGELOG.md
  vcd/provider.go
  vcd/resource_vcd_dnat.go
  vcd/resource_vcd_firewall_rules.go
  vcd/resource_vcd_snat.go
  website/docs/r/dnat.html.markdown
  website/docs/r/firewall_rules.html.markdown
  website/docs/r/snat.html.markdown
Labels: documentation, size/S

#513 New resource - vcd_org_group
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config.go
  vcd/provider.go
  vcd/resource_vcd_org_group.go
  vcd/resource_vcd_org_group_test.go
  vcd/testcheck_funcs_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg_administration.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/group.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp_network.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/org_group.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#511 Add implementation for vapp network firewall rules resource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/config.go
  vcd/provider.go
  vcd/resource_vcd_vapp_firewall_rules.go
  vcd/resource_vcd_vapp_firewall_rules_test.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_org_network.go
  vcd/structure.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/modules.txt
  website/docs/d/edgegateway.html.markdown
  website/docs/d/vapp.html.markdown
  website/docs/d/vapp_vm.html.markdown
  website/docs/r/vapp_firewall_rules.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#514 Affinity rules
  CHANGELOG.md
  go.mod
  go.sum
  scripts/staticcheck-config.sh
  vcd/datasource_test.go
  vcd/datasource_vcd_catalog.go
  vcd/datasource_vcd_catalog_item.go
  vcd/datasource_vcd_catalog_media.go
  vcd/datasource_vcd_edgegateway.go
  vcd/datasource_vcd_network_direct.go
  vcd/datasource_vcd_network_isolated.go
  vcd/datasource_vcd_network_routed.go
  vcd/datasource_vcd_vm_affinity_rule.go
  vcd/provider.go
  vcd/resource_vcd_network_routed.go
  vcd/resource_vcd_vm_affinity_rule.go
  vcd/resource_vcd_vm_affinity_rule_test.go
  vcd/structure.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/query_metadata.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm_affinity_rule.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/vm_affinity_rule.html.markdown
  website/docs/r/vm_affinity_rule.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#517 Add implementation for vapp network NAT rules resource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/provider.go
  vcd/resource_vcd_vapp_firewall_rules.go
  vcd/resource_vcd_vapp_firewall_rules_test.go
  vcd/resource_vcd_vapp_nat_rules.go
  vcd/resource_vcd_vapp_nat_rules_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp_network.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/vapp_firewall_rules.html.markdown
  website/docs/r/vapp_nat_rules.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#522 Fix docs 2.9
  CHANGELOG.md
  vcd/provider_unit_test.go
  website/docs/d/lb_server_pool.html.markdown
  website/docs/d/nsxv_dhcp_relay.html.markdown
  website/docs/r/lb_server_pool.html.markdown
  website/docs/r/nsxv_dhcp_relay.html.markdown
  website/docs/r/nsxv_firewall_rule.html.markdown
Labels: documentation, size/S

#520 Add implementation for vapp network static routing rules resource
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_vapp_network.go
  vcd/datasource_vcd_vapp_network_test.go
  vcd/datasource_vcd_vapp_org_network.go
  vcd/datasource_vcd_vapp_org_network_test.go
  vcd/provider.go
  vcd/resource_vcd_vapp_firewall_rules.go
  vcd/resource_vcd_vapp_firewall_rules_test.go
  vcd/resource_vcd_vapp_nat_rules.go
  vcd/resource_vcd_vapp_nat_rules_test.go
  vcd/resource_vcd_vapp_network.go
  vcd/resource_vcd_vapp_network_test.go
  vcd/resource_vcd_vapp_org_network.go
  vcd/resource_vcd_vapp_org_network_test.go
  vcd/resource_vcd_vapp_static_routing.go
  vcd/resource_vcd_vapp_static_routing_test.go
  vcd/resource_vcd_vapp_vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp_network.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/d/vapp_org_network.html.markdown
  website/docs/r/vapp_firewall_rules.html.markdown
  website/docs/r/vapp_nat_rules.html.markdown
  website/docs/r/vapp_network.html.markdown
  website/docs/r/vapp_org_network.html.markdown
  website/docs/r/vapp_static_routing.html.markdown
  website/vcd.erb
Labels: dependencies, documentation, size/XXL

#525 improve docs
  CHANGELOG.md
  scripts/runtest.sh
  scripts/skip-upgrade-tests.txt
  vcd/resource_vcd_vapp_network.go
Labels: size/XS

#526 add skip for upgrade test
  scripts/skip-upgrade-tests.txt
Labels: size/XS

#527 Add upgrade skips for tests
  scripts/skip-upgrade-tests.txt
Labels: size/XS
