Repository vmware/terraform-provider-vcd, pull requests merged in 2020-02, with the labels that each got.

#438 BUGFIX: `vcd_vapp_vm` `network` update causes existing NICs to change MAC addresses
  CHANGELOG.md
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  vcd/testcheck_funcs_test.go
Labels: size/M

#446 Fix/Unify data source behavior on Read errors
  CHANGELOG.md
  vcd/catalogitem.go
  vcd/config_test.go
  vcd/datasource_test.go
  vcd/datasource_vcd_catalog.go
  vcd/datasource_vcd_catalog_item.go
  vcd/datasource_vcd_catalog_media.go
  vcd/datasource_vcd_independent_disk.go
  vcd/datasource_vcd_org.go
  vcd/provider.go
  vcd/provider_unit_test.go
  vcd/resource_vcd_catalog_item.go
  vcd/resource_vcd_catalog_media.go
  vcd/resource_vcd_ipset.go
  vcd/resource_vcd_nsxv_dhcp_relay.go
Labels: size/XL

#443 Vdc flex
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_org_vdc.go
  vcd/datasource_vcd_org_vdc_test.go
  vcd/resource_vcd_org_vdc.go
  vcd/resource_vcd_org_vdc_test.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminorg.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/adminvdc.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/api_vcd_versions.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/edgegateway.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/org.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/system.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/types.go
  vendor/modules.txt
  website/docs/r/org_vdc.html.markdown
Labels: dependencies, documentation, size/XXL

#441 Add network adapter type support in vcd_vapp_vm resource and data source.
  CHANGELOG.md
  vcd/datasource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_multinetwork_test.go
  website/docs/r/vapp_vm.html.markdown
Labels: documentation, enhancement, size/M

#436 Add support for `network_dhcp_wait_seconds` in`vcd_vapp_vm`
  CHANGELOG.md
  go.mod
  go.sum
  vcd/datasource_vcd_vapp_vm.go
  vcd/helpers.go
  vcd/resource_vcd_edgegateway.go
  vcd/resource_vcd_vapp_vm.go
  vcd/resource_vcd_vapp_vm_dhcp_wait_test.go
  vcd/sample_vcd_test_config.json
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/catalog.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/media.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/nsxv_dhcplease.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/orgvdcnetwork.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/upload.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/uploadtask.go
  vendor/github.com/vmware/go-vcloud-director/v2/govcd/vm.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go
  vendor/github.com/vmware/go-vcloud-director/v2/types/v56/nsxv_types.go
  vendor/modules.txt
  website/docs/d/vapp_vm.html.markdown
  website/docs/r/independent_disk.html.markdown
  website/docs/r/vapp_vm.html.markdown
Labels: dependencies, documentation, enhancement, size/XXL

#453 Fix data race in client connection caching and add -race flag to tests
  CHANGELOG.md
  GNUmakefile
  scripts/runtest.sh
  vcd/config.go
Labels: bug, dependencies, size/M
